name: Build ACS LOGO and Release
on: ["workflow_dispatch"]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            acs_std_logo.tex
            acs_horizon_logo.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./fonts/*.otf
      
      - name: Convert PDF to SVG
        run: |
          sudo apt install -y pdf2svg
          pdf2svg acs_std_logo.pdf acs_std_logo.svg
          pdf2svg acs_horizon_logo.pdf acs_horizon_logo.svg

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            acs_std_logo.pdf
            acs_horizon_logo.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            acs_std_logo.pdf
            acs_horizon_logo.pdf
            acs_std_logo.svg
            acs_horizon_logo.svg
